targets:
  $default:
    builders:
      injectable_generator:injectable_builder:
        options:
          auto_register: true
          class_name_pattern: ".*UseCase$|.*Repository$|.*Bloc$|.*Service$"
          file_name_pattern: "_usecase$|_repository$|_bloc$|_service$"
      json_serializable:json_serializable:
        options:
          explicit_to_json: true
          include_if_null: false 